# Generated by Django 5.0.1 on 2024-01-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tb_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='unique_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hiv_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='', max_length=10),
        ),
    ]
